### ISSUE TITLE
nextjs: Update Text Layout to match design

### ISSUE THREAD

**Issue by tnn1t1s** [tnn1t1s/colorpunx#11]
![image](https://user-images.githubusercontent.com/3397401/149962172-eaa83fd9-ef19-4543-a5e0-fe172e6a7de9.png)

Note middle section with text.

**Comment by tnn1t1s** [comment]
Use fonts as folllows

Colorpunx: Montserrat, 400 - Normal, Size 44PX, Height 62PX
"Monochromatic digital artworks ...": Montserrat, 400 - Normal, Size 2
0PX, Height 34PX

Colorpunx are monochromatic ..." : Montserrate , 400 - Normal, Size 14
 PX, Height 25PX

**Comment by talentd1223** [comment]
![image](https://user-images.githubusercontent.com/97605845/150054329-3c1f3d91-472c-4ef3-bd15-0f85206874d4.png)
Could you please send me texts in red area?

**Comment by tnn1t1s** [comment]
Monochromatic digital artworks built from the Cryptopunks color palette.

ColorPunx are monochromatic NFT paintings sourced from the 222 unique colors used in the Larvalabs Cryptopunks. They are the first piece in the lineage of quantitative art history of early NFT works with work artifacts recorded on the blockchain. The Colorpunx are not affiliated with Larvalabs.

**Comment by tnn1t1s** [comment]
note: as per design 'The ColorPunx' should be centered (currently flush right)

**Comment by talentd1223** [comment]
I am not able to message you on Upwork. Can we chat over Telegram?
