### ISSUE TITLE
UX: On Colors page, update cryptopunk ID and 'used by' on carousel scroll.

### ISSUE THREAD

**Issue by tnn1t1s** [tnn1t1s/colorpunx#15]
![image](https://user-images.githubusercontent.com/3397401/150663215-5e7b6212-dd40-4833-a348-97b650f320fb.png)

**Comment by tnn1t1s** [comment]
also - remove the X out of Y in upper right.

**Comment by talentd1223** [comment]
Hi David, I am not able to message you on Upwork. Can we chat over Skype or Telegram?

**Comment by talentd1223** [comment]
Upwork limited my financial transaction.  I want to discuss about this with you.  Please let me know if you are available over Skype or Telegram.  Thank you.

**Comment by tnn1t1s** [comment]
you can mail at david.tinnitus@protonmail.com and i will get back
