### ISSUE TITLE
nextjs UI: update page contents on carousel scroll

### ISSUE THREAD

**Issue by tnn1t1s** [tnn1t1s/colorpunx#18]
when user scrolls thorugh carousel, either by arrows, slide, or thumbnails - update color name, list of punks and all other text.

**Comment by Muhammad-Bilal-7896** [comment]
Ok i will do that

**Comment by voigtito** [comment]
Hi, i have finished the issue! I contacted you on upwork. I have also made a few changes to improve the quality of the website.
