### ISSUE TITLE
Color Pages shows as 404 NOT FOUND

### ISSUE THREAD

**Issue by tnn1t1s** [tnn1t1s/colorpunx#9]
Fix issues with pages/[id].js not resolving. 

For example, https://colorpunx.io/colors/656361 should load the product page. It should be a static page created by `getStaticProps` and

**Comment by talentd1223** [comment]
![image](https://user-images.githubusercontent.com/97605845/150048532-9941116d-58e0-4ccc-81f5-e78eb413b0e1.png)

In previous version,  we can go those page by clicking avatar in red area.  But we don't have those avatars now.

**Comment by tnn1t1s** [comment]
yeah - should change so that we go to this page if click in the color (instead of going to opensea)
